/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function currentPlatform(): string

export declare function defaultModel(): string

export declare function englishPhraseTokens(text: string): Array<string>

export declare function englishWordTokens(text: string): Array<string>

export declare function hanNgramTokens(text: string, width: number): Array<string>

export declare function isVisionModel(model: string): boolean

export declare function keychainAccount(): string

export declare function keychainService(): string

export declare function loadApiKey(): string | null

export declare function macosKeychainAvailable(platform: string, securityPath?: string | undefined | null): boolean

/** Scores a task against a card's text; the card object carries nothing else. */
export declare function memoryScore(task: string, cardText: string): number

export declare function normalizeApiKey(value: string): string | null

export declare function normalizeMemoryText(text: string): string

/** Resolves an alias, a current model id, or one retired by the V4.1 line-up. */
export declare function resolveModel(value: string): string

export declare function saveApiKey(apiKey: string, platform?: string | undefined | null, securityPath?: string | undefined | null): void

export declare function supportedModels(): Array<string>
