/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Incremental server-sent-event framing.
 *
 * `TextDecoder` is fed with `{ stream: true }`, so a multi-byte character split
 * across two chunks stays intact; `take_utf8` reproduces that by holding an
 * incomplete trailing sequence until the next chunk arrives.
 */
export declare class SseReader {
  constructor()
  /** Feeds one chunk and returns every complete `data:` payload it completed. */
  push(chunk: Buffer): Array<string>
  /** Flushes the trailing line, mirroring the final `pending.trim()` pass. */
  finish(): string | null
}

/**
 * Streaming Markdown for a token-by-token answer. A line is held back until
 * the next one arrives, because a table separator only becomes recognisable
 * once the following line is known.
 */
export declare class StreamingMarkdownRenderer {
  constructor(color?: boolean | undefined | null)
  write(chunk: string): string
  finish(): string
}

export declare function assertImageCount(count: number): void

/** Rejects a text file that is too large to read or replace. */
export declare function assertTextSize(size: number): void

/** Builds the chat-completions request body. */
export declare function buildChatPayload(messagesJson: string, model: string, thinkingEnabled: boolean, reasoningEffort: string, maxTokens: number, toolsJson: string | undefined | null, stream: boolean): string

export declare function buildIcmInstruction(priorDraft: string): string

export declare function buildIcmSupplement(prior: string, supplement: string): string

export declare function buildSynthesisInstruction(packetsJson: string): string

/** Builds the system and user messages for one task. */
export declare function buildTaskMessages(task: string, memoryContext: string, extraInstruction: string, localEnabled: boolean, imagesJson: string): string

export declare function corePrompt(): string

export declare function currentPlatform(): string

/** Decodes file bytes as strict UTF-8, refusing NUL bytes as binary. */
export declare function decodeTextFile(bytes: Buffer): string

export declare function defaultModel(): string

export declare function detectImageMimeType(bytes: Buffer): string | null

export declare function englishPhraseTokens(text: string): Array<string>

export declare function englishWordTokens(text: string): Array<string>

/**
 * Validates an HTTP(S) image source and returns the normalised URL.
 *
 * Sources that are not HTTP(S) belong to the caller's other branches; the
 * local-file branch in particular stays in TypeScript.
 */
export declare function externalImageUrl(source: string): string

/** Validates a DeepSeek Files API image id and returns it unchanged. */
export declare function fileApiImageId(source: string): string

export declare function hanNgramTokens(text: string, width: number): Array<string>

/** The ICM marker is matched case-insensitively, mirroring `toLocaleLowerCase`. */
export declare function icmFollowUpNeeded(content: string): boolean

export declare function imageDataUrlPart(source: string): ImageDataUrlPart

/**
 * The canonical data URL and decoded byte count for an inline image source.
 * `detail` is validated by the caller and attached when the part is built.
 */
export interface ImageDataUrlPart {
  url: string
  bytes: number
}

/** Mirrors `/^https?:\/\//iu`: the transport gate the source branch uses. */
export declare function isHttpUrl(source: string): boolean

export declare function isImageDetail(value: string): boolean

/** Mirrors `/^[a-z][a-z0-9+.-]*:\/\//iu`: a scheme that is not HTTP(S). */
export declare function isSchemeUrl(source: string): boolean

/**
 * Policy for names that must never be read in local mode.
 *
 * The caller passes the lower-cased basename and the already-split path parts,
 * because splitting a path is Node path semantics rather than policy.
 */
export declare function isSensitiveFile(loweredBasename: string, pathParts: Array<string>): boolean

export declare function isTableSeparator(line: string): boolean

export declare function isVisionModel(model: string): boolean

export declare function keychainAccount(): string

export declare function keychainService(): string

export declare function loadApiKey(): string | null

export declare function localLimits(): LocalLimits

/** The size and count limits the local tools enforce. */
export interface LocalLimits {
  maxTextBytes: number
  maxListEntries: number
  maxSearchResults: number
  maxDiffLines: number
  maxAuditArchives: number
  auditLogMaxBytes: number
}

export declare function localPrompt(): string

/** The tool contracts advertised to the model in local mode. */
export declare function localToolDefinitions(): string

export declare function macosKeychainAvailable(platform: string, securityPath?: string | undefined | null): boolean

/** Scores a task against a card's text; the card object carries nothing else. */
export declare function memoryScore(task: string, cardText: string): number

export declare function normalizeApiKey(value: string): string | null

export declare function normalizeMemoryText(text: string): string

/** Parses a non-streaming reply into the `ModelReply` shape. */
export declare function parseModelReply(bodyJson: string): string

export declare function parseSearchResults(html: string): Array<SearchResult>

/**
 * Interprets one `data:` payload from the streaming response.
 *
 * A malformed payload is an error rather than a skipped event: the TypeScript
 * original lets `JSON.parse` throw, which fails the request instead of
 * silently dropping part of the answer.
 */
export declare function parseStreamChunk(data: string): StreamChunk

export declare function renderMarkdown(text: string, color: boolean): string

/** Resolves an alias, a current model id, or one retired by the V4.1 line-up. */
export declare function resolveModel(value: string): string

export declare function saveApiKey(apiKey: string, platform?: string | undefined | null, securityPath?: string | undefined | null): void

export interface SearchResult {
  title: string
  url: string
}

export declare function shouldUseWeb(task: string, webMode: string): boolean

export declare function singleAgentBudget(toaTokenBudget: number): SingleBudget

/** Token budget for a single answer. */
export interface SingleBudget {
  reserve: number
  maxTokens: number
}

/** One interpreted server-sent event. */
export interface StreamChunk {
  done: boolean
  content?: string
  reasoningContent?: string
  usageJson?: string
}

/** Removes the first ICM marker, as `replace` with a non-global pattern does. */
export declare function stripIcmMarker(content: string): string

export declare function stripTerminalControls(text: string): string

export declare function supportedModels(): Array<string>

export declare function tableCells(line: string): Array<string>

/**
 * Keeps the last `limit` bytes from the first complete line onwards, so an
 * archived audit log never starts mid-record.
 */
export declare function tailCompleteLines(data: Buffer, limit: number): Buffer

export declare function toaAgentBudget(toaTokenBudget: number, workers: number): ToaBudget

/** Token budget split for a Tree of Agents run. */
export interface ToaBudget {
  icmReserve: number
  workingBudget: number
  allocation: number
  synthesisBudget: number
}

/** Appends the explicit-web notice when the caller forced web search on. */
export declare function webRequiredInstruction(instruction: string, webMode: string): string

/** The instruction handed to one ToA worker. */
export declare function workerPrompt(role: string): string
